### ISSUE TITLE
Determine which method is crashing when running in parallel

### ISSUE THREAD

**Issue by adw96** [jacobbien/simulator#1]
Hi, Jacob,

First, this is a fantastic package and it has helped me a lot -- thanks so much for producing and maintaining it. 

I was wondering if there is any way to detect which method is crashing my simulation when running `run_method` in parallel. For example, here is a toy example with 2 methods, one of which randomly crashes. 

[test-crash.txt](https://github.com/jacobbien/simulator/files/1794239/test-crash.txt)

I would love to be able to determine which method is crashing, and be able to pull the simulated data that's crashing it so I can explore the behaviour of the method and debug. 

Can the `simulator` help me with this? 

Thanks for your help! 

Amy

**Comment by jacobbien** [comment]
Hi Amy,

Glad you're liking it!  Thanks for providing a minimal example demonstrating the behavior.  I've updated the package (on github, not CRAN yet) to address this issue.  The error message reports the method, model, and specific draw in which the error was thrown.  Also, it provides code that can be run for the user to rerun that precise function call on the set of data that led to the error. 
 Because methods are sometimes randomized (as in your example), one line of that provided code resets the random number generator to its state immediately before the method led to that error.

**Comment by jacobbien** [comment]
One minor (and unrelated) thing about your example... it was also producing a warning about the labels not being unique across different models.  This was occurring because you had
sprintf("Some data with n=", n) rather than paste0("Some data with n=", n) or sprintf("Some data with n=%s", n)

**Comment by adw96** [comment]
Thank you so much, Jacob! I just used this again on a different issue and I was able to decipher immediately what was causing the problem. Much appreciated! The simulator is 🔥😃

Thanks also for pointing out the cause of the labelling warning!
