### ISSUE TITLE
large parameter values error

### ISSUE THREAD

**Issue by adw96** [jacobbien/simulator#3]
Hi Jacob! When using large parameter values, I get a mysterious error message that took me a long time to debug. The issue is that the files are written to, e.g., normal_random_variables/n_1e+05/model.Rdata, which fails is_valid_component_name. Can scipen in options() be temporarily changed?

I know I can have n_over_a_thousand as an input instead, so I'm reporting this to help people in future from spending as much time as I did time debugging that mysterious error. 

Thanks for your help!

```
make_data <- function(n) {
  new_model(name = "normal_random_variables",
            label = sprintf("Some data with n=", n),
            params = list(n = n),
            simulate = function(n, nsim) {
              replicate(nsim, rnorm(n), simplify=F)
            })
}
mysterious_error <- new_simulation(name = "large-values",
                                   label = "Large values break even the best software") %>%
  generate_model(make_data, seed = 1,
                 n = as.list(c(1e3, 1e4, 1e5, 1e6)),
                 vary_along = c("n")) 
```

**Comment by jacobbien** [comment]
Hi Amy,

Thanks for another helpful comment and for again providing a minimal example demonstrating the behavior. I've fixed this issue in the latest commit d0b3124852e4060322fa605f2b5e1fc5bd4d20ae. If you rerun your example, it now produces a warning about the labels not being unique across different models. This is because you had
sprintf("Some data with n=", n) rather than paste0("Some data with n=", n) or sprintf("Some data with n=%s", n)

Best,
Jacob
