### ISSUE TITLE
simple simulation is too slow

### ISSUE THREAD

**Issue by AhmedAliStats** [jacobbien/simulator#5]
First of all, thank you very much for this package. I really like its modularity.

I am running a simple toy simulation to assess the performance of the sample mean at sample sizes 5, 10 and 15 if the underlying distribution is standard Gaussian. Unfortunately, the simulation is taking a lot more time than I expected.

If I implement the simulation using the package "SimDesign", I get the following benchmark for 1000 replicates
```
   user  system elapsed 
   1.93    0.37    2.47
```

while for the "simulator" package, I am getting
```
user  system elapsed 
 333.61    0.08  334.13
```

Here's the code that I am using
```
#MSE of the sample mean
library(SimDesign)
library(simulator)

#SimDesign implementation

n <- c(5, 10, 15)

Design <- expand.grid(n = n)

Generate <- function(condition, fixed_objects = NULL){
  rnorm(n = condition$n)
}

Analyse <- function(condition, dat, fixed_objects = NULL){
  mean(dat)
}

Summarise <- function(condition, results, fixed_objects = NULL){
  c(MSE = mean(results^2))
}

system.time(results <- runSimulation(design = Design, replications = 1000, generate = Generate, analyse = Analyse, summarise = Summarise))      

#simulator implementation
make_normal_model <- function(n){
  new_model(name = "normal", label = sprintf("N(0, 1) with sample size %s", n), params = list(n = n), simulate = function(n, nsim){
    Y <- replicate(n = nsim, expr = rnorm(n = n))
    return(split(Y, col(Y)))
  })
}

mean_method <- new_method(name = "mean", label = "Sample Mean", method = function(model, draw){
  mean(draw)
})

squaredError_metric <- new_metric(name = "se", label = "Squared Error", metric = function(model, out){
  return((out$out)^2)})

system.time({sim <- new_simulation(name = "mean", label = "mean") %>% generate_model(make_normal_model, n = list(5, 10, 15), vary_along = "n") %>% simulate_from_model(nsim = 1000) %>% run_method(methods = list(mean_method)) %>% evaluate(metrics = list(squaredError_metric))})

tabulate_eval(sim, metric_name = "se")
```

I would really appreciate it if you can point me to where the problem lies or if this is an issue with the simulator.

PS: I am using R version 3.6.0 on a PC with Win 10 x64, Core i3, (magnetic) HDD and 4GB RAM.
Also, the problem seems to be with the "run_method" part as it takes much longer time than simulating the data and applying the metric.

Thank you.

**Comment by jacobbien** [comment]
Thanks for your comment, @AhmedAliStats, and for including a specific simple example!  The new version of the simulator fixes this issue.  You should find that your example now runs in the same amount of time using the simulator as with SimDesign (on my laptop they both complete in less than half a second).  Thanks for your interest in the simulator, and I hope you find it useful for your simulations!

Interesting side note: The culprit, it turns out, was `system.time({...})`, which the simulator had been using to measure the runtime of the users' methods.  This was leading to a staggering amount of garbage collection.  Now the simulator measures the runtime much more efficiently.
